### PR TITLE
signal handling

### PR DESCRIPTION
**Pull request by zippy**
This PR adds ability to install signal handlers on players.  See readme for instructions.

### CODE REVIEW

**Review by Connoropolous — APPROVED** [review]
Looks good.

**Comment by Connoropolous** [comment]
CI does seem to be failing though... are tests passing locally?

**Comment by zippy** [comment]
Looks like install holochain is failing now... not surprising.  I'll look into that.

**Comment by zippy** [comment]
Looks like rust version was old.  Can't wait till holonix lands and CI becomes more predictable!

**Pull request merged**
